server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Route 1: Auth Service (Không chặn Filter)
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          
        # Route 2: Product Service (Có chặn Filter)
        - id: product-service
          uri: http://localhost:8081 
          predicates:
            - Path=/products/**, /categories/**
          filters:
            - AuthenticationFilter
            
        # Route 3: Order Service (MỚI - Có chặn Filter)
        - id: order-service
          uri: http://localhost:8083  # Port của Order Service
          predicates:
            - Path=/api/orders/** # Khớp với đường dẫn Controller bên Order
          filters:
            - AuthenticationFilter    # Filter sẽ kiểm tra Token (trừ khi nằm trong whitelist RouteValidator)