server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Route 1: Auth Service (Không chặn Filter)
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          
        # Route 2: Product Service (Có chặn Filter)
        - id: product-service
          uri: http://localhost:8081 # Giả sử product chạy port 8081
          predicates:
            - Path=/products/**, /categories/**
          filters:
            - AuthenticationFilter # Tên class Filter của bạn
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/** # Mọi request bắt đầu bằng /orders sẽ sang OrderService

        # --- PAYMENT SERVICE (THÊM MỚI) ---
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/payments/** #